"""Added Many-to-Many relationships <PostTag>

Revision ID: 477970003b64
Revises: 090ba46ab7d4
Create Date: 2020-05-31 13:28:41.482996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477970003b64'
down_revision = '090ba46ab7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('tag_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tag')
    # ### end Alembic commands ###
