"""Added profile information

Revision ID: 81942401688a
Revises: 58ce60ab5129
Create Date: 2020-06-17 23:23:50.250196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81942401688a'
down_revision = '58ce60ab5129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
